name: Master Branch Build

on:
  push:
    branches:
      - master

jobs:
  mvnBuild:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Maven Build
        run: |
          bash bot.sh rebuild
          echo ::set-env name=JAR_FILE::$(find bot/target -name "td-user-bot.jar")
      - name: Upload Jar
        uses: actions/upload-artifact@master
        with:
          name: td-user-bot
          path: ${{ env.JAR_FILE }}